# Numpy vs PyTorch for Linear Algebra 
[link](https://rickwierenga.com/blog/machine%20learning/numpy-vs-pytorch-linalg.html)

## Why PyTorch?
- GPU acceleration
-  integration with other parts of the PyTorch framework
- mainly used in deep learning which requires heavy matrix computation
- two arguments : device_type (whether the computation happens on CPU or GPU) and the requires_grad (which is used to compute the derivatives).

In [1]:
import torch

## Why Numpy?
- quick experimentation and small projects
- light weight framework
- mainly used in typical machine learning algorithms

In [2]:
import numpy as np

## Using Both

In [ ]:
# Numpy -> Pytorch
tensor = torch.from_numpy(np_array)

# Pytorch -> Numpy
ndarray = tensor.numpy()

## New tensors

In [7]:
# numpy
zeros = np.zeros((4,4))
ones = np.ones((4,4))
random = np.random.random((4,4))

print(zeros)
print(ones)
print(random)

print("--------------")
# PyTorch
zeros = torch.zeros(4,4)
ones = torch.ones(4,4)
random = torch.rand(4,4)

print(zeros)
print(ones)
print(random)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.84674019 0.86122292 0.47916101 0.05073224]
 [0.81579483 0.5845992  0.42265437 0.19553312]
 [0.48595474 0.45783618 0.16816105 0.047586  ]
 [0.30908543 0.29020462 0.52134135 0.08433093]]
--------------
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.8511, 0.2944, 0.0356, 0.1390],
        [0.9051, 0.0047, 0.0700, 0.6737],
        [0.1548, 0.6376, 0.5867, 0.7869],
        [0.7036, 0.3835, 0.4178, 0.9937]])


## Basic Linear Algebra
### Indexing

In [ ]:
# Numpy
# Index item
array[0, 0] # returns a float

# Index row
array[0, :] # returns an array

# Pytorch
# Index item
torch[0, 0] # returns a tensor

# Index row
torch[0, :] # returns a tensor

### Addition & subtraction

In [ ]:
# Numpy
array + array2
array - array2

# Pytorch
tensor + tensor2
tensor - tensor2

### (Element wise) multiplication

In [ ]:
# Numpy
# Element wise
array * array

# Matrix multiplication
array @ array

# Pytorch
# Element wise
tensor * tensor

# Matrix multiplication
tensor @ tensor

### Shape and dimensions

In [ ]:
# Numpy
shap    = array.shape
num_dim = array.ndim

# Pytorch
shape   = tensor.shape
shape   = tensor.size() # equal to `.shape`
num_dim = tensor.dim()

### Reshaping

In [ ]:
# Numpy
new_array = array.reshape((8, 2))

# Pytorch
new_tensor = tensor.view(8, 2)

### Determinant

In [ ]:
# Numpy
np.linalg.det(array)

# Pytorch
# not natively supported

### Inverse and Moore-Pensore inverse


In [ ]:
# Numpy
# Inverse
np.linalg.inv(array)

# Moore Pensore inverse
np.linalg.pinv(array)

# Pytorch
# Inverse
tensor.inverse()

# Moore Pensore inverse
tensor.pinverse()

### Sum/mean/std
These functions return floating point numbers in Numpy where PyTorch returns 1 by 1 tensors.

In [ ]:
# Numpy
# Sum
array.sum()

# Mean
array.mean()

# Standard Deviation
array.std()

# Pytorch
# Sum
tensor.sum()

# Mean
tensor.mean()

# Standard Deviation
tensor.std()

### Transpose

In [ ]:
# Numpy
array.T
array.transpose()

# Pytorch
tensor.t()

## Saving to disk

In [ ]:
# Numpy
np.save('file.npy', array)
np.load('file.npy')

# Pytorch
torch.save(tensor, 'file')
torch.load('file')

## Using the GPU

In [ ]:
# put the tensor in GPU memory
gpu_tensor = tensor.gpu()